import {OFFICIAL_DISTANCES,GATE_DISTANCES,validateCalibration,interpolateCross,crossed,robustVelocity,peakVelocity,StartDetector,qualityScore,readiness,fitProjectiveMap} from './core.js';
import {APP_VERSION} from './config.js'; import {CameraController,StabilityMonitor} from './camera.js'; import {createPoseLandmarker,extractPose,drawPose} from './vision.js'; import {loadDB,saveDB,saveResult,saveVideo,getVideo,personalBest,previousResult,exportCSV,addAthlete,deleteAthlete,clearResults} from './storage.js';
const $=id=>document.getElementById(id), DB={stream:null,pose:null,raf:0,direction:1,gates:{0:.08,5:.28,10:.50,20:.88},calibrated:false,tiltOk:false,stableOk:false,detected:false,lastPose:null,prevPose:null,startDetector:null,armed:false,running:false,finished:false,startT:null,tracks:[],gateTimes:{5:null,10:null,20:null},frameCount:0,validFrames:0,stableSamples:[],recorder:null,chunks:[],recording:false};
const screens={measure:$('measureScreen'),result:$('resultScreen'),history:$('historyScreen'),athletes:$('athletesScreen'),videos:$('videosScreen')};
const camera=new CameraController($('video'),()=>{});const stability=new StabilityMonitor($('video'));
const fmt=x=>Number.isFinite(x)?x.toFixed(3):'—';const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function show(k){Object.values(screens).forEach(x=>x.classList.remove('active'));screens[k].classList.add('active');if(k==='history')renderHistory();if(k==='athletes')renderAthletes();if(k==='videos')renderVideos()}
function selected(){const d=loadDB();return d.athletes.find(a=>a.id===$('athlete').value)||d.athletes[0]}
function populate(){const d=loadDB();$('athlete').innerHTML=d.athletes.map(a=>`<option value="${esc(a.id)}">${esc(a.name)}</option>`).join('')}
function calibrationOK(){return validateCalibration(DB.gates,DB.direction).valid}
function setCheck(id,ok,text){const e=$(id);e.textContent=(ok?'● ':'○ ')+text;e.classList.toggle('ok',ok)}
function readinessUI(){const r=readiness({camera:camera.isActive(),level:DB.tiltOk,stable:DB.stableOk,model:!!DB.pose,athlete:DB.detected,calibration:DB.calibrated,direction:DB.direction,gates:DB.gates});setCheck('cCam',r.camera,'Cámara');setCheck('cLevel',r.level,'Nivel');setCheck('cStable',r.stable,'Estable');setCheck('cBody',r.model&&r.athlete,'IA / Atleta');$('status').textContent=!r.camera?'ACTIVA LA CÁMARA':!r.model?'CARGANDO IA':!r.athlete?'BUSCANDO ATLETA':!r.calibration?'CALIBRA LOS GATES':!r.valid?'VALIDANDO':'LISTO PARA SALIR';$('statusSub').textContent=r.valid?'Todo automático. Corre cuando estés listo.':'ARS bloquea la medición hasta que la escena sea válida.';if(r.valid&&!DB.armed&&!DB.running)autoArm()}
async function activate(){try{await camera.start();DB.stream=camera.stream;DB.tiltOk=false;DB.stableOk=false;DB.detected=false;$('camButton').hidden=true;$('bodyStatus').textContent='● IA CARGANDO';DB.pose=await createPoseLandmarker();$('bodyStatus').textContent='● IA ACTIVA';startLoop()}catch(e){console.error(e);$('bodyStatus').textContent='● IA/CÁMARA NO DISPONIBLE';$('bodyStatus').classList.add('error');alert('ARS SPRINT no pudo iniciar cámara o IA. Usa HTTPS/localhost y concede permisos.')}}
function orientation(e){const b=Number(e.beta),g=Number(e.gamma);if(!Number.isFinite(b)||!Number.isFinite(g))return;const a=Math.abs(Number(screen.orientation?.angle||0));const tilt=a%180===0?Math.min(Math.abs(b),Math.abs(Math.abs(g)-90)):Math.min(Math.abs(Math.abs(b)-90),Math.abs(g));DB.tiltOk=tilt<7;$('tilt').textContent=`Nivel ${tilt.toFixed(1)}°`;setCheck('cLevel',DB.tiltOk,'Nivel')}
function fitCanvas(){const c=$('overlay'),v=$('video'),r=v.getBoundingClientRect(),d=devicePixelRatio||1;c.width=Math.max(1,r.width*d);c.height=Math.max(1,r.height*d);return[r.width,r.height,d]}
function draw(){const [w,h,d]=fitCanvas(),ctx=$('overlay').getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);for(const m of GATE_DISTANCES){const x=DB.gates[m];const hit=m>0&&DB.gateTimes[m]!=null;ctx.strokeStyle=m===0?'#fff':hit?'#62ed90':'#d8dde2';ctx.lineWidth=hit?3:2;ctx.setLineDash(m===0?[]:[7,6]);ctx.beginPath();ctx.moveTo(x*w,h*.98);ctx.lineTo(.5*w,.48*h);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#05080bdd';ctx.fillRect(x*w-24,12,48,22);ctx.fillStyle='#fff';ctx.font='900 11px system-ui';ctx.textAlign='center';ctx.fillText(m+' m',x*w,27)}drawPose(ctx,DB.lastPose,w,h)}
function startLoop(){cancelAnimationFrame(DB.raf);const loop=t=>{DB.raf=requestAnimationFrame(loop);if(!DB.pose||$('video').readyState<2)return;const v=$('video');DB.frameCount++;const s=stability.sample();DB.stableSamples.push(s);if(DB.stableSamples.length>90)DB.stableSamples.shift();DB.stableOk=s>=.58;try{const res=DB.pose.detectForVideo(v,t);const p=extractPose(res,v,DB.direction);DB.prevPose=DB.lastPose;DB.lastPose=p;DB.detected=!!p&&p.conf>=.45;if(p)DB.validFrames++;readinessUI();if(DB.detected)processFrame(p,t);draw();$('track').textContent=`Tracking ${p?Math.round(p.conf*100):0}%`;$('fps').textContent='LIVE'}catch(e){console.warn(e)}};DB.raf=requestAnimationFrame(loop)}
function processFrame(p,t){if(!DB.armed||DB.finished)return;if(!DB.startDetector)DB.startDetector=new StartDetector({gateX:DB.gates[0],direction:DB.direction});if(!DB.running){const r=DB.startDetector.update(p,t);if(r.started){DB.running=true;DB.startT=t;DB.tracks=[{x:p.x,t}];DB.gateTimes={5:null,10:null,20:null};$('runState').textContent='SPRINT';startRecorder();return}}
if(DB.running){const prev=DB.tracks.at(-1);const curr={x:p.x,t};DB.tracks.push(curr);if(DB.tracks.length>360)DB.tracks.shift();for(const m of OFFICIAL_DISTANCES){if(DB.gateTimes[m]!=null)continue;const gx=DB.gates[m];if(prev&&crossed(prev,curr,gx,DB.direction)){const ct=interpolateCross(prev,curr,gx);if(ct!=null){DB.gateTimes[m]=(ct-DB.startT)/1000;$('s'+m).textContent=fmt(DB.gateTimes[m])}}}const target=Number($('distance').value);if(DB.gateTimes[target]!=null)finish()}}
function autoArm(){DB.armed=true;DB.finished=false;DB.startDetector=new StartDetector({gateX:DB.gates[0],direction:DB.direction,near:.065,stableFrames:6,required:4,minForward:.0015});$('status').textContent='LISTO PARA SALIR';$('statusSub').textContent='El cronómetro arrancará con tu primer movimiento real.'}
function confirmCal(){if(!calibrationOK())return alert('Calibración inválida. Revisa el orden 0/5/10/20 m.');DB.calibrated=true;draw();readinessUI()}
function reset(){DB.gates={0:.08,5:.28,10:.50,20:.88};DB.calibrated=false;DB.armed=false;DB.running=false;DB.finished=false;draw();readinessUI()}
function flip(){DB.direction*=-1;DB.calibrated=false;DB.armed=false;$('direction').textContent=DB.direction>0?'→':'←';draw();readinessUI()}
function startRecorder(){if(!window.MediaRecorder||!DB.stream)return;const types=['video/mp4;codecs=h264','video/webm;codecs=vp9','video/webm'];const mime=types.find(x=>MediaRecorder.isTypeSupported?.(x));if(!mime)return;try{DB.chunks=[];DB.recorder=new MediaRecorder(DB.stream,{mimeType:mime,videoBitsPerSecond:8000000});DB.recorder.ondataavailable=e=>e.data.size&&DB.chunks.push(e.data);DB.recorder.start(200);DB.recording=true;$('record').textContent='● GRABANDO'}catch{}}
function stopRecorder(){return new Promise(resolve=>{if(!DB.recording||!DB.recorder)return resolve(null);const r=DB.recorder;r.onstop=()=>{DB.recording=false;resolve(new Blob(DB.chunks,{type:r.mimeType||'video/webm'}))};try{r.stop()}catch{resolve(null)}})}
async function finish(){if(DB.finished)return;DB.finished=true;DB.running=false;const blob=await stopRecorder();const dist=Number($('distance').value),vel=robustVelocity(DB.tracks,DB.gates,DB.direction,12),peak=peakVelocity(vel),ratio=DB.validFrames/Math.max(1,DB.frameCount),continuity=Math.min(1,DB.tracks.length/Math.max(1,DB.frameCount*.65)),stable=DB.stableSamples.length?DB.stableSamples.reduce((a,b)=>a+b,0)/DB.stableSamples.length:0,q=qualityScore({validRatio:ratio,stableScore:stable,gateCount:OFFICIAL_DISTANCES.filter(x=>DB.gateTimes[x]!=null).length,trackingContinuity:continuity}),a=selected();const rec={id:crypto.randomUUID?.()||String(Date.now()),date:new Date().toISOString(),athleteId:a.id,athlete:a.name,category:a.category,team:a.team,distance:dist,attempt:Number($('attempt').value)||1,t5:DB.gateTimes[5],t10:DB.gateTimes[10],t20:DB.gateTimes[20],vmax:peak?.v??null,vmaxAt:peak?.m??null,quality:q.label,qualityScore:q.score,frames:DB.frameCount,validFrames:DB.validFrames,profile:vel.map(z=>({t:(z.t-DB.startT)/1000,m:z.m,v:z.v})),videoId:null};saveResult(rec);if(blob)rec.videoId=await saveVideo(rec.id,blob);const d=loadDB();const idx=d.results.findIndex(x=>x.id===rec.id);if(idx>=0){d.results[idx]=rec;saveDB(d)}showResult(rec)}
async function showResult(r){show('resultScreen');$('resultTitle').textContent=`${r.athlete} · ${r.distance} m`;$('resultSub').textContent=new Date(r.date).toLocaleString('es-PE');$('r5').textContent=fmt(r.t5)+' s';$('r10').textContent=fmt(r.t10)+' s';$('r20').textContent=fmt(r.t20)+' s';$('rv').textContent=Number.isFinite(r.vmax)?(r.vmax*3.6).toFixed(2)+' km/h':'—';$('rvAt').textContent=Number.isFinite(r.vmaxAt)?`Vmax ≈ ${r.vmaxAt.toFixed(1)} m`:'';const pb=personalBest(r.athleteId,r.distance,r.id),prev=previousResult(r.athleteId,r.distance,r.id);$('quality').textContent=r.quality;$('frames').textContent=`${r.validFrames}/${r.frames}`;$('pb').textContent=pb?fmt(pb['t'+r.distance])+' s':'Primer registro';$('prev').textContent=prev?fmt(prev['t'+r.distance])+' s':'Primer intento';$('videoReview').innerHTML=r.videoId?'<button id="playVideo" class="primary">▶ REVISAR VÍDEO</button>':'<span>Vídeo no disponible</span>';if(r.videoId)$('playVideo').onclick=async()=>{const b=await getVideo(r.videoId);if(b){const u=URL.createObjectURL(b);$('videoReview').innerHTML=`<video controls playsinline src="${u}"></video>`}}}
function renderHistory(){const d=loadDB();$('historyBody').innerHTML=d.results.map(r=>`<tr><td>${new Date(r.date).toLocaleDateString('es-PE')}</td><td>${esc(r.athlete)}</td><td>${r.distance} m</td><td>${fmt(r.t5)}</td><td>${fmt(r.t10)}</td><td>${fmt(r.t20)}</td><td>${Number.isFinite(r.vmax)?(r.vmax*3.6).toFixed(2)+' km/h':'—'}</td><td>${r.quality}</td></tr>`).join('')||'<tr><td colspan="8">Sin resultados.</td></tr>'}
function renderAthletes(){const d=loadDB();$('athleteRows').innerHTML=d.athletes.map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.category)}</td><td>${esc(a.team)}</td><td><button class="ghost" data-del="${a.id}">Eliminar</button></td></tr>`).join('')}
function renderVideos(){const d=loadDB();$('videoRows').innerHTML=d.results.filter(r=>r.videoId).map(r=>`<tr><td>${new Date(r.date).toLocaleDateString('es-PE')}</td><td>${esc(r.athlete)}</td><td>${r.distance} m</td><td><button class="ghost" data-v="${r.videoId}">▶ Ver</button></td></tr>`).join('')||'<tr><td colspan="4">Sin vídeos.</td></tr>'}
function bindGates(){document.querySelectorAll('[data-gate]').forEach(el=>{const m=Number(el.dataset.gate);let drag=false;el.addEventListener('pointerdown',e=>{if(DB.calibrated)return;drag=true;el.setPointerCapture(e.pointerId)});el.addEventListener('pointermove',e=>{if(!drag)return;const r=$('video').getBoundingClientRect();DB.gates[m]=Math.max(.02,Math.min(.98,(e.clientX-r.left)/r.width));DB.calibrated=false;draw();});el.addEventListener('pointerup',()=>{drag=false})})}
$('camButton').onclick=activate;$('confirmCal').onclick=confirmCal;$('reset').onclick=reset;$('flip').onclick=flip;$('settings').onclick=()=>{$('settingsPanel').hidden=!$('settingsPanel').hidden};$('distance').onchange=()=>{DB.calibrated=false;DB.armed=false;readinessUI()};$('directionSelect').onchange=e=>{if(!DB.calibrated){DB.direction=e.target.value==='forward'?1:-1;$('direction').textContent=DB.direction>0?'→':'←';draw()}};$('newSprint').onclick=()=>{reset();show('measureScreen')};$('historyNav').onclick=()=>show('historyScreen');$('athleteNav').onclick=()=>show('athletesScreen');$('videoNav').onclick=()=>show('videosScreen');$('historyNav2').onclick=()=>show('historyScreen');$('setupNav').onclick=()=>show('measureScreen');$('export').onclick=exportCSV;$('clear').onclick=()=>{if(confirm('¿Borrar resultados?')){clearResults();renderHistory()}};$('addAthlete').onclick=()=>{const n=$('newName').value.trim();if(!n)return;addAthlete({name:n,category:$('newCategory').value.trim()||'General',team:$('newTeam').value.trim()});populate();renderAthletes()};$('athleteRows').onclick=e=>{const id=e.target.dataset.del;if(id&&confirm('¿Eliminar atleta?')){deleteAthlete(id);populate();renderAthletes()}};$('videoRows').onclick=async e=>{const id=e.target.dataset.v;if(!id)return;const b=await getVideo(id);if(b){const u=URL.createObjectURL(b);$('videoViewer').innerHTML=`<video controls playsinline src="${u}"></video>`}};
window.addEventListener('deviceorientation',orientation,{passive:true});populate();$('version').textContent=APP_VERSION;draw();readinessUI();bindGates();
