import {OFFICIAL_DISTANCES,GATE_DISTANCES,validateCalibration,interpolateCross,crossed,interpolateCross2D,crossedGate2D,robustVelocity,peakVelocity,StartDetector,qualityScore,readiness} from './core.js';
import {APP_VERSION} from './config.js'; import {CameraController,StabilityMonitor} from './camera.js'; import {createPoseLandmarker,extractPose,drawPose} from './vision.js'; import {loadDB,saveDB,saveResult,saveVideo,getVideo,personalBest,previousResult,exportCSV,addAthlete,deleteAthlete,clearResults} from './storage.js';
const $=id=>document.getElementById(id), DB={stream:null,pose:null,raf:0,direction:1,gates:{0:.08,5:.28,10:.50,20:.88},calibrated:false,tiltOk:false,stableOk:false,detected:false,tiltSeen:false,tiltManual:false,orientationTimer:null,lastPose:null,prevPose:null,startDetector:null,armed:false,running:false,finished:false,startT:null,tracks:[],gateTimes:{5:null,10:null,20:null},frameCount:0,validFrames:0,stableSamples:[],recorder:null,chunks:[],recording:false,distanceBeforeRun:20,athleteBeforeRun:'a1'};
const screens={measure:$('measureScreen'),result:$('resultScreen'),history:$('historyScreen'),athletes:$('athletesScreen'),videos:$('videosScreen')};
const camera=new CameraController($('video'),()=>{});const stability=new StabilityMonitor($('video'));
const fmt=x=>Number.isFinite(x)?x.toFixed(3):'—';const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function show(k){const key=screens[k]?k:(k==='resultScreen'?'result':k.replace('Screen',''));const screen=screens[key];if(!screen){console.warn('ARS screen inexistente',k);return false}Object.values(screens).forEach(x=>x.classList.remove('active'));screen.classList.add('active');if(key==='history'){renderHistory();renderComparison();}if(key==='athletes')renderAthletes();if(key==='videos')renderVideos();return true}
function selected(){const d=loadDB();return d.athletes.find(a=>a.id===$('athlete').value)||d.athletes[0]}
function populate(){const d=loadDB();$('athlete').innerHTML=d.athletes.map(a=>`<option value="${esc(a.id)}">${esc(a.name)}</option>`).join('')}
function calibrationOK(){return validateCalibration(DB.gates,DB.direction).valid}
function setCheck(id,ok,text){const e=$(id);e.textContent=(ok?'● ':'○ ')+text;e.classList.toggle('ok',ok)}
function readinessUI(){const r=readiness({camera:camera.isActive(),level:DB.tiltOk,stable:DB.stableOk,model:!!DB.pose,athlete:DB.detected,calibration:DB.calibrated,direction:DB.direction,gates:DB.gates});setCheck('cCam',r.camera,'Cámara');setCheck('cLevel',r.level,'Nivel');setCheck('cStable',r.stable,'Estable');setCheck('cBody',r.model&&r.athlete,'IA / Atleta');$('status').textContent=!r.camera?'ACTIVA LA CÁMARA':!r.model?'CARGANDO IA':!r.athlete?'BUSCANDO ATLETA':!r.calibration?'CALIBRA LOS GATES':!r.valid?'VALIDANDO':'LISTO PARA SALIR';$('statusSub').textContent=r.valid?'Todo automático. Corre cuando estés listo.':'ARS bloquea la medición hasta que la escena sea válida.';if(r.valid&&!DB.armed&&!DB.running)autoArm()}
async function activate(){try{await camera.start();DB.stream=camera.stream;DB.tiltOk=false;DB.tiltSeen=false;DB.tiltManual=false;DB.stableOk=false;DB.detected=false;clearTimeout(DB.orientationTimer);DB.orientationTimer=setTimeout(()=>{if(!DB.tiltSeen){DB.tiltManual=true;DB.tiltOk=true;$('tilt').textContent='Nivel manual';setCheck('cLevel',true,'Nivel manual')}},2500);$('camButton').hidden=true;$('bodyStatus').textContent='● IA CARGANDO';DB.pose=await createPoseLandmarker();$('bodyStatus').textContent='● IA ACTIVA';$('bodyStatus').classList.remove('error');startLoop()}catch(e){console.error('ARS INIT',e);const msg=String(e?.message||e||'Error desconocido');$('bodyStatus').textContent=msg.includes('MediaPipe')||msg.includes('PoseLandmarker')?'● IA NO DISPONIBLE':'● CÁMARA NO DISPONIBLE';$('bodyStatus').classList.add('error');$('status').textContent='REVISAR INICIO';$('statusSub').textContent=msg.slice(0,180);if(!camera.isActive())$('camButton').hidden=false;alert('ARS SPRINT: '+msg)}}
function orientation(e){DB.tiltSeen=true;DB.tiltManual=false;const b=Number(e.beta),g=Number(e.gamma);if(!Number.isFinite(b)||!Number.isFinite(g))return;const a=Math.abs(Number(screen.orientation?.angle||0));const tilt=a%180===0?Math.min(Math.abs(b),Math.abs(Math.abs(g)-90)):Math.min(Math.abs(Math.abs(b)-90),Math.abs(g));DB.tiltOk=tilt<7;$('tilt').textContent=`Nivel ${tilt.toFixed(1)}°`;setCheck('cLevel',DB.tiltOk,'Nivel')}
function fitCanvas(){const c=$('overlay'),v=$('video'),r=v.getBoundingClientRect(),d=devicePixelRatio||1;c.width=Math.max(1,Math.round(r.width*d));c.height=Math.max(1,Math.round(r.height*d));return[r.width,r.height,d]}
function syncGateHandles(w,h){document.querySelectorAll('[data-gate]').forEach(el=>{const m=Number(el.dataset.gate);el.style.left=(DB.gates[m]*100)+'%';el.style.top=(m===0?'98%':'48%');el.textContent=m+' m';el.classList.toggle('hit',m>0&&DB.gateTimes[m]!=null);el.classList.toggle('target',m===Number($('distance')?.value||20));el.style.pointerEvents=DB.calibrated?'none':'auto'})}
function draw(){const [w,h,d]=fitCanvas(),ctx=$('overlay').getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);const target=Number($('distance')?.value||20);for(const m of GATE_DISTANCES){const x=DB.gates[m];const hit=m>0&&DB.gateTimes[m]!=null;const active=m===target;ctx.strokeStyle=m===0?'#fff':hit?'#62ed90':active?'#fff':'#d8dde2';ctx.lineWidth=hit?4:active?3:2;ctx.setLineDash(m===0||active?[]:[7,6]);ctx.beginPath();ctx.moveTo(x*w,h*.98);ctx.lineTo(.5*w,.48*h);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=active?'#62ed90':'#05080bdd';ctx.fillRect(x*w-28,12,56,24);ctx.fillStyle=active?'#031007':'#fff';ctx.font='900 11px system-ui';ctx.textAlign='center';ctx.fillText(m+' m',x*w,28)}drawPose(ctx,DB.lastPose,w,h);syncGateHandles(w,h)}
function updateLiveUI(t){const target=Number($('distance')?.value||20);$('targetReadout').textContent=`OBJETIVO ${target} m`;document.querySelectorAll('[data-live-distance]').forEach(el=>el.classList.toggle('target',Number(el.dataset.liveDistance)===target));const live=$('liveHud');if(live)live.classList.toggle('active',DB.running||DB.armed);if(DB.running&&DB.startT!=null)$('elapsed').textContent=fmt((t-DB.startT)/1000);else if(!DB.running)$('elapsed').textContent='0.000'}
function startLoop(){cancelAnimationFrame(DB.raf);const loop=t=>{DB.raf=requestAnimationFrame(loop);if(!DB.pose||$('video').readyState<2)return;updateLiveUI(t);const v=$('video');DB.frameCount++;const s=stability.sample();DB.stableSamples.push(s);if(DB.stableSamples.length>90)DB.stableSamples.shift();DB.stableOk=s>=.58;try{const res=DB.pose.detectForVideo(v,t);const p=extractPose(res,v,DB.direction);DB.prevPose=DB.lastPose;DB.lastPose=p;DB.detected=!!p&&p.conf>=.45;if(p)DB.validFrames++;readinessUI();if(DB.detected)processFrame(p,t);draw();$('track').textContent=`Tracking ${p?Math.round(p.conf*100):0}%`;$('fps').textContent='LIVE'}catch(e){console.warn(e)}};DB.raf=requestAnimationFrame(loop)}
function processFrame(p,t){if(!DB.armed||DB.finished)return;if(!DB.startDetector)DB.startDetector=new StartDetector({gateX:DB.gates[0],direction:DB.direction});if(!DB.running){const r=DB.startDetector.update(p,t);if(r.started){DB.running=true;DB.startT=t;DB.tracks=[{x:p.x,t}];DB.gateTimes={5:null,10:null,20:null};['s5','s10','s20'].forEach(id=>$(id).textContent='—');$('runState').textContent='SPRINT';$('status').textContent=`CORRIENDO · OBJETIVO ${Number($('distance').value)} m`;startRecorder();return}}
if(DB.running){const prev=DB.tracks.at(-1);const curr={x:p.x,t};DB.tracks.push(curr);if(DB.tracks.length>360)DB.tracks.shift();for(const m of OFFICIAL_DISTANCES){if(DB.gateTimes[m]!=null)continue;const gx=DB.gates[m];if(prev&&crossedGate2D(prev,curr,gx,DB.direction)){const ct=interpolateCross2D(prev,curr,gx,DB.direction);if(ct!=null){DB.gateTimes[m]=(ct-DB.startT)/1000;$('s'+m).textContent=fmt(DB.gateTimes[m]);$('live-splits')?.classList.add('has-result')}}}const target=Number($('distance').value);if(DB.gateTimes[target]!=null)finish()}}
function autoArm(){DB.armed=true;DB.finished=false;DB.startDetector=new StartDetector({gateX:DB.gates[0],direction:DB.direction,near:.065,stableFrames:6,required:4,minForward:.0015});$('runState').textContent='LISTO';$('status').textContent='LISTO PARA SALIR';$('statusSub').textContent='El cronómetro arrancará con tu primer movimiento real.'}
function confirmCal(){if(!calibrationOK())return alert('Calibración inválida. Revisa el orden 0/5/10/20 m.');DB.calibrated=true;draw();readinessUI()}
async function reset(){if(DB.running||DB.recording)await stopRecorder();DB.gates={0:.08,5:.28,10:.50,20:.88};DB.calibrated=false;DB.tiltSeen=false;DB.tiltManual=false;DB.tiltOk=false;clearTimeout(DB.orientationTimer);DB.armed=false;DB.running=false;DB.finished=false;DB.startT=null;DB.tracks=[];DB.gateTimes={5:null,10:null,20:null};DB.frameCount=0;DB.validFrames=0;DB.stableSamples=[];DB.startDetector=null;DB.lastPose=null;DB.prevPose=null;['s5','s10','s20'].forEach(id=>$(id).textContent='—');$('runState').textContent='LISTO';$('record').textContent='● Vídeo listo';draw();readinessUI()}
function flip(){DB.direction*=-1;DB.calibrated=false;DB.armed=false;const el=$('directionSelect');if(el)el.value=DB.direction>0?'forward':'reverse';draw();readinessUI()}
function startRecorder(){if(!window.MediaRecorder||!DB.stream)return;const types=['video/mp4;codecs=h264','video/webm;codecs=vp9','video/webm'];const mime=types.find(x=>MediaRecorder.isTypeSupported?.(x));if(!mime)return;try{DB.chunks=[];DB.recorder=new MediaRecorder(DB.stream,{mimeType:mime,videoBitsPerSecond:8000000});DB.recorder.ondataavailable=e=>e.data.size&&DB.chunks.push(e.data);DB.recorder.start(200);DB.recording=true;$('record').textContent='● GRABANDO'}catch{}}
function stopRecorder(){return new Promise(resolve=>{if(!DB.recording||!DB.recorder)return resolve(null);const r=DB.recorder;r.onstop=()=>{DB.recording=false;resolve(new Blob(DB.chunks,{type:r.mimeType||'video/webm'}))};try{r.stop()}catch{resolve(null)}})}
function estimateAcceleration(vel){if(!vel||vel.length<2)return null;let max=null;for(let i=1;i<vel.length;i++){const dt=(vel[i].t-vel[i-1].t)/1000;if(dt<=0)return null;const a=(vel[i].v-vel[i-1].v)/dt;if(Number.isFinite(a)&&(!max||a>max))max=a}return Number.isFinite(max)?max:null}
async function finish(){if(DB.finished)return;DB.finished=true;DB.running=false;const blob=await stopRecorder();const dist=Number($('distance').value);if(!Number.isFinite(DB.gateTimes[dist])){DB.finished=false;DB.running=false;return}const vel=robustVelocity(DB.tracks,DB.gates,DB.direction,12),peak=peakVelocity(vel),ratio=DB.validFrames/Math.max(1,DB.frameCount),continuity=Math.min(1,DB.tracks.length/Math.max(1,DB.frameCount*.65)),stable=DB.stableSamples.length?DB.stableSamples.reduce((a,b)=>a+b,0)/DB.stableSamples.length:0,q=qualityScore({validRatio:ratio,stableScore:stable,gateCount:OFFICIAL_DISTANCES.filter(x=>x<=dist&&DB.gateTimes[x]!=null).length,trackingContinuity:continuity}),a=selected();const rec={id:crypto.randomUUID?.()||String(Date.now()),date:new Date().toISOString(),athleteId:a.id,athlete:a.name,category:a.category,team:a.team,distance:dist,attempt:Number($('attempt').value)||1,t5:DB.gateTimes[5],t10:DB.gateTimes[10],t20:DB.gateTimes[20],vmax:peak?.v??null,vmaxAt:peak?.m??null,acceleration:estimateAcceleration(vel),quality:q.label,qualityScore:q.score,frames:DB.frameCount,validFrames:DB.validFrames,profile:vel.map(z=>({t:(z.t-DB.startT)/1000,m:z.m,v:z.v})),videoId:null};saveResult(rec);if(blob)rec.videoId=await saveVideo(rec.id,blob);$('record').textContent=rec.videoId?'● Vídeo guardado':'● Vídeo no disponible';const d=loadDB();const idx=d.results.findIndex(x=>x.id===rec.id);if(idx>=0){d.results[idx]=rec;saveDB(d)}showResult(rec)}
function drawResultCurve(profile){const c=$('profileChart');if(!c)return;const dpr=window.devicePixelRatio||1,w=c.clientWidth||640,h=c.clientHeight||220;c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);if(!profile?.length)return;const xs=profile.map(z=>z.m),ys=profile.map(z=>z.v).filter(Number.isFinite);const xmin=Math.min(...xs),xmax=Math.max(...xs, xmin+1e-6),ymax=Math.max(...ys,1);ctx.strokeStyle='#9aa4ad';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(36,h-30);ctx.lineTo(w-12,h-30);ctx.moveTo(36,12);ctx.lineTo(36,h-30);ctx.stroke();ctx.strokeStyle='#62ed90';ctx.lineWidth=3;ctx.beginPath();profile.forEach((z,i)=>{const x=36+(z.m-xmin)/(xmax-xmin)*(w-52);const y=h-30-(Math.max(0,z.v)/ymax)*(h-50);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#fff';ctx.font='12px system-ui';ctx.fillText('Velocidad (m/s)',42,22);ctx.fillText('Distancia (m)',w-105,h-10)}

async function showResult(r){show('result');$('resultTitle').textContent=`${r.athlete} · ${r.distance} m`;$('resultSub').textContent=new Date(r.date).toLocaleString('es-PE');$('r5').textContent=fmt(r.t5)+' s';$('r10').textContent=fmt(r.t10)+' s';$('r20').textContent=fmt(r.t20)+' s';$('rv').textContent=Number.isFinite(r.vmax)?(r.vmax*3.6).toFixed(2)+' km/h':'—';$('rvAt').textContent=Number.isFinite(r.vmaxAt)?`Vmax ≈ ${r.vmaxAt.toFixed(1)} m`:'';const pb=personalBest(r.athleteId,r.distance,r.id),prev=previousResult(r.athleteId,r.distance,r.id);$('quality').textContent=r.quality;$('frames').textContent=`${r.validFrames}/${r.frames}`;$('pb').textContent=pb?fmt(pb['t'+r.distance])+' s':'Primer registro';$('prev').textContent=prev?fmt(prev['t'+r.distance])+' s':'Primer intento';drawResultCurve(r.profile);$('videoReview').innerHTML=r.videoId?'<button id="playVideo" class="primary">▶ REVISAR VÍDEO</button>':'<span>Vídeo no disponible</span>';if(r.videoId)$('playVideo').onclick=async()=>{const b=await getVideo(r.videoId);if(b){const u=URL.createObjectURL(b);$('videoReview').innerHTML=`<video controls playsinline src="${u}"></video>`}}}
function renderHistory(){const d=loadDB();$('historyBody').innerHTML=d.results.map(r=>`<tr><td>${new Date(r.date).toLocaleDateString('es-PE')}</td><td>${esc(r.athlete)}</td><td>${r.distance} m</td><td>${fmt(r.t5)}</td><td>${fmt(r.t10)}</td><td>${fmt(r.t20)}</td><td>${Number.isFinite(r.vmax)?(r.vmax*3.6).toFixed(2)+' km/h':'—'}</td><td>${r.quality}</td></tr>`).join('')||'<tr><td colspan="8">Sin resultados.</td></tr>'}
function renderComparison(){
  const out=$('comparisonBody');
  if(!out)return;
  const athlete=selected();
  const dist=Number($('distance').value);
  if(!athlete){out.textContent='No hay atleta seleccionado.';return}
  const rows=loadDB().results.filter(r=>r.athleteId===athlete.id&&r.distance===dist&&Number.isFinite(r['t'+dist])).sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,2);
  if(rows.length<2){out.textContent='Se necesitan al menos dos registros válidos para comparar.';return}
  const [a,b]=rows;
  const ta=a['t'+dist],tb=b['t'+dist];
  const dv=Number.isFinite(a.vmax)&&Number.isFinite(b.vmax)?a.vmax-b.vmax:null;
  const pct=tb?((ta-tb)/tb*100):null;
  const change=pct==null?'—':(pct>=0?'+':'')+pct.toFixed(1)+'%';
  const vmaxDelta=dv==null?'—':(dv>=0?'+':'')+dv.toFixed(2)+' m/s';
  out.innerHTML='<div class="comparison-grid"><div><span>Actual</span><b>'+fmt(ta)+' s</b></div><div><span>Anterior</span><b>'+fmt(tb)+' s</b></div><div><span>Cambio tiempo</span><b>'+change+'</b></div><div><span>Δ Vmax</span><b>'+vmaxDelta+'</b></div></div><small>'+new Date(a.date).toLocaleDateString('es-PE')+' vs '+new Date(b.date).toLocaleDateString('es-PE')+'</small>';
}
function renderAthletes(){const d=loadDB();$('athleteRows').innerHTML=d.athletes.map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.category)}</td><td>${esc(a.team)}</td><td><button class="ghost" data-del="${a.id}">Eliminar</button></td></tr>`).join('')}
function renderVideos(){const d=loadDB();$('videoRows').innerHTML=d.results.filter(r=>r.videoId).map(r=>`<tr><td>${new Date(r.date).toLocaleDateString('es-PE')}</td><td>${esc(r.athlete)}</td><td>${r.distance} m</td><td><button class="ghost" data-v="${r.videoId}">▶ Ver</button></td></tr>`).join('')||'<tr><td colspan="4">Sin vídeos.</td></tr>'}
function bindGates(){document.querySelectorAll('[data-gate]').forEach(el=>{const m=Number(el.dataset.gate);let drag=false;el.addEventListener('pointerdown',e=>{if(DB.calibrated)return;drag=true;el.setPointerCapture(e.pointerId)});el.addEventListener('pointermove',e=>{if(!drag)return;const r=$('video').getBoundingClientRect();DB.gates[m]=Math.max(.02,Math.min(.98,(e.clientX-r.left)/r.width));DB.calibrated=false;draw();});el.addEventListener('pointerup',()=>{drag=false})})}
$('camButton').onclick=activate;$('confirmCal').onclick=confirmCal;$('reset').onclick=reset;$('flip').onclick=flip;$('settings').onclick=()=>{$('settingsPanel').hidden=!$('settingsPanel').hidden};$('athlete').onfocus=()=>{DB.athleteBeforeRun=$('athlete').value};$('athlete').onchange=()=>{if(DB.running){$('athlete').value=DB.athleteBeforeRun;return}DB.athleteBeforeRun=$('athlete').value};$('distance').onfocus=()=>{DB.distanceBeforeRun=Number($('distance').value)};$('distance').onchange=()=>{if(DB.running){$('distance').value=String(DB.distanceBeforeRun);$('distanceLabel').textContent=$('distance').value+' m';return}DB.distanceBeforeRun=Number($('distance').value);DB.calibrated=false;DB.armed=false;document.querySelectorAll('[data-live-distance]').forEach(el=>el.classList.toggle('target',Number(el.dataset.liveDistance)===Number($('distance').value)));$('distanceLabel').textContent=$('distance').value+' m';draw();readinessUI()};$('directionSelect').onchange=e=>{if(DB.running){e.target.value=DB.direction>0?'forward':'reverse';return}if(!DB.calibrated){DB.direction=e.target.value==='forward'?1:-1;draw();readinessUI()}};$('newSprint').onclick=async()=>{await reset();show('measureScreen')};$('athleteNav').onclick=()=>show('athletesScreen');$('videoNav').onclick=()=>show('videosScreen');$('historyNav2').onclick=()=>show('historyScreen');$('setupNav').onclick=()=>show('measureScreen');$('export').onclick=exportCSV;$('compareNow').onclick=renderComparison;$('clear').onclick=()=>{if(confirm('¿Borrar resultados?')){clearResults();renderHistory()}};$('addAthlete').onclick=()=>{const n=$('newName').value.trim();if(!n)return;addAthlete({name:n,category:$('newCategory').value.trim()||'General',team:$('newTeam').value.trim()});populate();renderAthletes()};$('athleteRows').onclick=e=>{const id=e.target.dataset.del;if(id&&confirm('¿Eliminar atleta?')){deleteAthlete(id);populate();renderAthletes()}};$('videoRows').onclick=async e=>{const id=e.target.dataset.v;if(!id)return;const b=await getVideo(id);if(b){const u=URL.createObjectURL(b);$('videoViewer').innerHTML=`<video controls playsinline src="${u}"></video>`}};
window.addEventListener('deviceorientation',orientation,{passive:true});populate();$('version').textContent=APP_VERSION;draw();readinessUI();bindGates();
