from pathlib import Path
p=Path('/mnt/data/v32fix/app.js')
s=p.read_text()
s=s.replace('const state={stream:null,pose:null,raf:0,armed:false,running:false,finished:false,calibrated:false,poseLoading:false,direction:1,gates:{0:.10,5:.30,10:.50,20:.90},tracks:[],filtered:null,startT:null,recorder:null,chunks:[],recording:false,gateTimes:{5:null,10:null,20:null},frameCount:0,validFrames:0,lastRaw:null,moveSamples:0,stableHistory:[]};', '''const state={stream:null,pose:null,raf:0,armed:false,running:false,finished:false,calibrated:false,poseLoading:false,direction:1,gates:{0:.10,5:.30,10:.50,20:.90},tracks:[],filtered:null,startT:null,recorder:null,chunks:[],recording:false,gateTimes:{5:null,10:null,20:null},frameCount:0,validFrames:0,lastRaw:null,moveSamples:0,stableHistory:[],stableScore:0,preStartX:null,preStartY:null,lastProcessT:null};''')
s=s.replace('function syncReadiness(){const body=!!state.pose,cam=!!state.stream,cal=state.calibrated;', 'function syncReadiness(){const body=!!state.pose,cam=!!state.stream,cal=state.calibrated;')
# replace loop with camera-stability + robust pose handling
start=s.index('async function loop(){')
end=s.index('\nfunction gatePointer', start)
new_loop='''async function loop(){\n if(!state.pose||!$("video").videoWidth){state.raf=requestAnimationFrame(loop);return}\n const now=performance.now();\n try{\n  const res=state.pose.detectForVideo($("video"),now),p=point(res);\n  state.lastRaw=p;\n  drawCalibration();\n  updateCameraStability();\n  if(p){\n   $("checkAthlete").textContent=state.armed||state.running?"● Atleta fijado":"● Atleta detectado";\n   $("checkAthlete").classList.add("ok");\n   if(state.armed)process(p,now);\n  }else{\n   $("checkAthlete").textContent="○ Atleta no detectado";\n   $("checkAthlete").classList.remove("ok");\n  }\n  syncReadiness();\n }catch(e){console.warn("Pose frame error",e)}\n state.raf=requestAnimationFrame(loop)\n}\nlet stabilityCanvas=null,stabilityCtx=null,lastStabilitySample=null;\nfunction updateCameraStability(){\n if(state.running)return;\n const v=$("video"); if(!v.videoWidth||!v.videoHeight)return;\n if(!stabilityCanvas){stabilityCanvas=document.createElement("canvas");stabilityCanvas.width=32;stabilityCanvas.height=18;stabilityCtx=stabilityCanvas.getContext("2d",{willReadFrequently:true})}\n try{\n  // Sample the upper/background band to avoid the athlete as much as possible.\n  stabilityCtx.drawImage(v,0,0,32,18);\n  const data=stabilityCtx.getImageData(0,0,32,10).data;\n  let diff=0,n=0;\n  if(lastStabilitySample){for(let i=0;i<data.length;i+=4){diff+=Math.abs(data[i]-lastStabilitySample[i])+Math.abs(data[i+1]-lastStabilitySample[i+1])+Math.abs(data[i+2]-lastStabilitySample[i+2]);n+=3}}\n  lastStabilitySample=data;\n  const score=n?Math.max(0,1-diff/(n*18)):1;\n  state.stableHistory.push(score); if(state.stableHistory.length>12)state.stableHistory.shift();\n  state.stableScore=state.stableHistory.reduce((a,b)=>a+b,0)/state.stableHistory.length;\n  const ok=state.stableScore>.86;\n  $("checkStable").textContent=(ok?"● ":"○ ")+"Cámara estable"; $("checkStable").classList.toggle("ok",ok);\n  $("stableIndicator").textContent=`Estabilidad: ${ok?"OK":"Ajustar"}`;\n }catch(e){}\n}\n'''
s=s[:start]+new_loop+s[end:]
# replace process function
start=s.index('function process(raw,now){')
end=s.index('\nasync function finish()', start)
new_process='''function process(raw,now){\n const p=smooth(raw,now),prev=state.tracks.at(-1);\n state.frameCount++;\n if(p.conf<.58)return;\n state.validFrames++;\n $("trackConfidence").textContent=`Tracking: ${(p.conf*100).toFixed(0)}%`;\n const dt=prev?(now-prev.t)/1000:0;\n if(dt>0&&dt<.2)$("frameRate").textContent=`FPS: ${(1/dt).toFixed(0)}`;\n const dx=prev?state.direction*(p.x-prev.x):0;\n const near=Math.abs(state.direction*(p.x-state.gates[0]))<.085;\n if(!state.running){\n   // Require a stable athlete near 0 m, then several consecutive forward frames.\n   if(near){\n     if(!state.preStartX){state.preStartX=p.x;state.preStartY=p.y;state.moveSamples=0}\n     const forward=dx>.0025;\n     state.moveSamples=forward?state.moveSamples+1:Math.max(0,state.moveSamples-1);\n     $("runState").textContent=state.moveSamples>=2?"LISTO PARA SALIR":"LISTO PARA SALIR";\n     $("runHint").textContent="Corre cuando estés preparado";\n     if(state.moveSamples>=3){\n       state.running=true; state.startT=now; state.tracks=[{t:now,x:p.x,y:p.y,c:p.conf}]; state.lastProcessT=now;\n       $("runState").textContent="SPRINT"; $("runHint").textContent="Atleta en movimiento";\n     }\n   }else{\n     state.preStartX=null;state.preStartY=null;state.moveSamples=0;\n     $("runState").textContent="BUSCANDO ATLETA";\n     $("runHint").textContent="Coloca al atleta en 0 m…";\n   }\n   if(!state.running)return;\n }\n state.tracks.push({t:now,x:p.x,y:p.y,c:p.conf});\n const elapsed=(now-state.startT)/1000; $("liveTime").textContent=Math.max(0,elapsed).toFixed(3);\n [5,10,20].forEach(g=>{\n   if(state.gateTimes[g]!=null)return;\n   const gx=state.gates[g];\n   const cross=state.direction>0?p.x>=gx:p.x<=gx;\n   const was=prev&&(state.direction>0?prev.x<gx:prev.x>gx);\n   if(cross&&was){\n     const span=Math.abs(p.x-prev.x);\n     const ratio=span?Math.abs(gx-prev.x)/span:1;\n     const ct=prev.t+Math.max(0,Math.min(1,ratio))*(now-prev.t);\n     state.gateTimes[g]=(ct-state.startT)/1000;\n     $("split"+g).textContent=fmt(state.gateTimes[g]);\n   }\n });\n const target=Number($("distanceSelect").value);\n if(state.gateTimes[target]!=null)finish();\n}\n'''
s=s[:start]+new_process+s[end:]
# replace finish velocity engine with stronger smoothed derivative and gate-derived fallback only if no profile
start=s.index('async function finish(){')
end=s.index('\nfunction stopRecorder()', start)
new_finish='''async function finish(){\n if(state.finished)return; state.finished=true; state.running=false; state.armed=false;\n await stopRecorder();\n const d=Number($("distanceSelect").value),times=state.gateTimes;\n const samples=state.tracks.filter(x=>x.t>=state.startT&&x.c>=.58);\n const refs=[0,5,10,20].map(m=>({m,x:state.gates[m]})).filter(r=>r.m<=d);\n function pxToM(px){for(let i=1;i<refs.length;i++){const a=refs[i-1],b=refs[i];if((px>=a.x&&px<=b.x)||(px<=a.x&&px>=b.x))return a.m+(px-a.x)/(b.x-a.x||1)*(b.m-a.m)}return NaN}\n const rawVel=[];\n for(let i=1;i<samples.length;i++){\n   const a=samples[i-1],b=samples[i],dt=(b.t-a.t)/1000; if(dt<=.005||dt>.12)continue;\n   const ma=pxToM(a.x),mb=pxToM(b.x); if(!Number.isFinite(ma)||!Number.isFinite(mb))continue;\n   const v=Math.abs(mb-ma)/dt; if(v>0&&v<12)rawVel.push({v,m:mb,t:b.t});\n }\n // Median window suppresses pose jitter while preserving the true acceleration peak.\n const vel=[];\n for(let i=0;i<rawVel.length;i++){const lo=Math.max(0,i-2),hi=Math.min(rawVel.length,i+3);const w=rawVel.slice(lo,hi).map(z=>z.v).sort((a,b)=>a-b);vel.push({v:w[Math.floor(w.length/2)],m:rawVel[i].m,t:rawVel[i].t})}\n let peak=vel.reduce((best,z)=>!best||z.v>best.v?z:best,null);\n const ratio=state.validFrames/Math.max(state.frameCount,1);\n const quality=ratio>.88&&state.stableScore>.82?"Buena":ratio>.65?"Aceptable":"Limitada";\n const rec={date:new Date().toISOString(),athlete:$("athleteSelect").selectedOptions[0]?.text||"Atleta 1",distance:d,t5:times[5],t10:times[10],t20:times[20],vmax:peak?.v??null,vmaxAt:peak?.m??null,frames:state.frameCount,validFrames:state.validFrames,quality,profile:vel.map(z=>({t:(z.t-state.startT)/1000,m:z.m,v:z.v})).filter(z=>z.m>=0&&z.m<=d)};\n const data=db();data.results.unshift(rec);saveDB(data);showResult(rec);\n}\n'''
s=s[:start]+new_finish+s[end:]
# Ensure reset on arm
s=s.replace('state.gateTimes={5:null,10:null,20:null};$("split5")', 'state.gateTimes={5:null,10:null,20:null};state.preStartX=null;state.preStartY=null;state.moveSamples=0;state.stableHistory=[];state.stableScore=0;$("split5")')
# make calibration quality stricter: require spacing progression not absurd
old='if(!increasing||gaps.some(g=>g<.04)||Math.abs(xs[3]-xs[0])<.35){'
new='const d05=Math.abs(xs[1]-xs[0]),d510=Math.abs(xs[2]-xs[1]),d1020=Math.abs(xs[3]-xs[2]);const spacingOk=d05>.035&&d510>.035&&d1020>.035; if(!increasing||!spacingOk||Math.abs(xs[3]-xs[0])<.35){'
s=s.replace(old,new)
p.write_text(s)
